### ISSUE TITLE
Feature: Sync search and URL parameters

### ISSUE THREAD

**Issue by pBouillon** [BuiltWithAnalog/builtwithanalog#61]
### Type of feature

✨ Feature

### Current behavior

When selecting filters, none are persisted in the URL. It makes it impossible to share/bookmark.

### Suggested solution

It could be great to add filters on the URL upon selection and restore them on startup if any has been set:

![query params suggestion](https://github.com/user-attachments/assets/0b043df6-5046-4dd8-9f5d-80342530801f)

### I would be willing to submit a PR to fix this issue

- [X] Yes and I have read the [Contribution Guide](https://github.com/TechShowcase/builtwithanalog/blob/main/CONTRIBUTING.md) and I agree to follow this project's [Code of Conduct](https://github.com/TechShowcase/builtwithanalog/blob/main/CODE_OF_CONDUCT.md)
- [ ] No

**Comment by monacodelisa** [comment]
@pBouillon that is a great suggestion :) 
yes tbh I didn't even think that far, but I like it I will assign you if you would like to implement it that would be great
